apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miage-bank
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/guillaume-helg/rendu-devops-2026.git'
    path: tp-buildah-trivy-dive-helm/miage-bank
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: miage-bank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
