apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "miage-bank.fullname" . }}-config-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miage-bank.labels" . | nindent 4 }}
    component: config
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "miage-bank.selectorLabels" . | nindent 6 }}
      component: config
