apiVersion: v1
kind: Service
metadata:
  name: {{ include "miage-bank.fullname" . }}-customer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miage-bank.selectorLabels" . | nindent 4 }}
    component: customer
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "miage-bank.selectorLabels" . | nindent 4 }}
    component: customer
