apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miage-bank.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miage-bank.selectorLabels" . | nindent 4 }}
    component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "miage-bank.selectorLabels" . | nindent 6 }}
      component: gateway
  template:
    metadata:
      labels:
        {{- include "miage-bank.selectorLabels" . | nindent 8 }}
        component: gateway
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        {{- include "miage-bank.waitForDiscovery" . | nindent 8 }}
        {{- include "miage-bank.waitForConfigServer" . | nindent 8 }}
      containers:
        - name: gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://{{ include "miage-bank.fullname" . }}-config:8888/"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://{{ include "miage-bank.fullname" . }}-discovery:8761/eureka/"
          startupProbe:
            httpGet:
              path: /actuator/health/startup
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
              scheme: HTTP
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
            timeoutSeconds: 2
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir: {}
