{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "miage-bank.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miage-bank.selectorLabels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
    secretName: {{ include "miage-bank.fullname" . }}-tls
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if $.Values.frontend.enabled }}
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "miage-bank.fullname" $ }}-frontend
                port:
                  number: 3000
          {{- end }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "miage-bank.fullname" $ }}-gateway
                port:
                  number: 8080
          {{- if $.Values.frontend.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "miage-bank.fullname" $ }}-frontend
                port:
                  number: 3000
          {{- end }}
    {{- end }}
{{- end }}
