{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "miage-bank.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "miage-bank.selectorLabels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "miage-bank.fullname" $ }}-gateway
                port:
                  number: 8080
          {{- if $.Values.frontend.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "miage-bank.fullname" $ }}-frontend
                port:
                  number: 3000
          {{- end }}
    {{- end }}
{{- end }}
