{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "miage-bank.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "miage-bank.selectorLabels" . | nindent 6 }}
      component: gateway
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "miage-bank.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "miage-bank.selectorLabels" . | nindent 6 }}
      component: config
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
{{- end }}
