replicaCount: 1

image:
  repository: ghcr.io/guillaume-helg/miage-bank-backend
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  name: "miage-bank-sa"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: miage-bank.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

config:
  springProfile: "default"
  extra: {}

vault:
  secretPath: "secret/data/miage-bank"
