{{- if .Values.mongodb.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongodb-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
    component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mongodb.persistence.storageClass }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size | quote }}
{{- end }}
