{{- if .Values.mysql.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "database.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
    component: mysql
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mysql.persistence.storageClass }}
  storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size | quote }}
{{- end }}
