mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  service:
    port: 3306
  rootPassword: ${MYSQL_ROOT_PASSWORD}
  database: ${MYSQL_DATABASE}
  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi

mongodb:
  image:
    repository: mongo
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    port: 27017
  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi
